# Generated by Django 4.2 on 2023-05-16 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_accounts_updated_at_alter_accounts_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounts',
            old_name='blocked',
            new_name='is_blocked',
        ),
    ]
