# Generated by Django 4.1.3 on 2023-05-27 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipping_price',
        ),
    ]
