# Generated by Django 4.1.3 on 2023-06-25 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0012_rename_username_artist_artistname_and_more'),
        ('userapp', '0003_order_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='artist',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='artist.artist'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='slot_no',
            field=models.IntegerField(null=True),
        ),
    ]
