# Generated by Django 4.1.3 on 2023-06-25 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_booking_artist_alter_booking_booking_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booking_price',
        ),
    ]
