# Generated by Django 4.1.3 on 2023-06-25 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_remove_booking_booking_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_time',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_type',
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
