# Generated by Django 4.1.3 on 2023-06-26 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0013_event_booking_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userapp', '0006_remove_payment_payment_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='artist',
            field=models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='artist.artist'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
