# Generated by Django 4.1.3 on 2023-06-26 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0007_alter_booking_artist_alter_booking_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='artist',
            new_name='artistname',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='event',
            new_name='eventname',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='user',
            new_name='username',
        ),
    ]
