# Generated by Django 4.1.3 on 2023-06-27 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0008_rename_artist_booking_artistname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(default='razorpay', max_length=100),
        ),
    ]
