# Generated by Django 4.1.3 on 2023-07-05 04:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0005_address_artist_alter_address_user'),
        ('artist', '0013_event_booking_price'),
        ('userapp', '0009_alter_booking_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.AddField(
            model_name='order',
            name='art_seller',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='art_seller', to='artist.artist'),
        ),
        migrations.AddField(
            model_name='order',
            name='artist_buyer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artist_buyer', to='artist.artist'),
        ),
        migrations.AddField(
            model_name='order',
            name='user_buyer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='booking',
            name='artistname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='artist.artist'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='post',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='artist.post'),
        ),
    ]
