# Generated by Django 4.1.3 on 2023-07-05 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0013_event_booking_price'),
        ('accounts', '0005_address_artist_alter_address_user'),
        ('userapp', '0010_remove_order_artist_remove_order_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='art_seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='art_seller', to='artist.artist'),
        ),
        migrations.AlterField(
            model_name='order',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artist.post'),
        ),
    ]
