# Generated by Django 4.1.3 on 2023-07-07 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0014_event_created_at'),
        ('userapp', '0011_alter_order_address_alter_order_art_seller_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='artistname',
        ),
        migrations.AddField(
            model_name='booking',
            name='artist_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artist_name', to='artist.artist'),
        ),
        migrations.AddField(
            model_name='booking',
            name='bookingartist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookingartist', to='artist.artist'),
        ),
    ]
