# Generated by Django 4.2 on 2023-05-09 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=13)),
                ('place', models.CharField(max_length=100)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('blocked', models.BooleanField(default=False)),
            ],
        ),
    ]
