# Generated by Django 4.2 on 2023-05-20 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0003_artist_created_at_artist_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='blocked',
            new_name='is_blocked',
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art_content', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='images')),
                ('base_price', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artist.artist')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100, unique=True)),
                ('event_date', models.DateField()),
                ('event_place', models.CharField(max_length=100)),
                ('event_start_time', models.TimeField()),
                ('event_end_time', models.TimeField()),
                ('total_slots', models.IntegerField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('conducting_artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artist.artist')),
            ],
        ),
    ]
