# Generated by Django 4.1.3 on 2023-05-27 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0004_rename_blocked_artist_is_blocked_post_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='shipping_price',
            field=models.FloatField(null=True),
        ),
    ]
