# Generated by Django 4.1.3 on 2023-06-08 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0007_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='profile_img',
            field=models.ImageField(default=True, upload_to='profiles'),
        ),
    ]
