# Generated by Django 4.1.3 on 2023-06-16 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0008_artist_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='profile_img',
            field=models.ImageField(default=True, null=True, upload_to='profiles'),
        ),
    ]
