# Generated by Django 4.1.3 on 2023-06-20 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0010_alter_artist_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='from_google',
            field=models.BooleanField(default=False),
        ),
    ]
