# Generated by Django 4.1.3 on 2023-06-25 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0012_rename_username_artist_artistname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='booking_price',
            field=models.FloatField(default=True),
        ),
    ]
