# Generated by Django 4.1.3 on 2023-07-08 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0014_event_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='cover_img',
            field=models.ImageField(null=True, upload_to='profiles'),
        ),
    ]
